version: '3.4'

services:
  seng513-frontend:
    image: seng513-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
